### PR TITLE
Fix link in README

### PR DESCRIPTION
**Pull request by tmcneal**
Thank you @lucgagan for adding an acknowledgement. This updates the link to point to the correct URL.

Best of luck on your project.

### CODE REVIEW

**Comment by lucgagan** [comment]
Of course. I don't know if you saw this update, but I've shared an apology in a few places.

https://github.com/lucgagan/auto-playwright/issues/15#issuecomment-1816458559

In reflection, my stance was not appropriate.

**Comment by tmcneal** [comment]
I saw that - much appreciated.

**Comment by yyx990805** [comment]
You guys are awesome <3 @tmcneal @lucgagan. Your situation here is a true guiding light how to solve such issues.

**Comment by lucgagan** [comment]
I am not exactly proud of how I navigated this, but this was a valuable lesson. It gave me an opportunity to reflect not only on my communication, but also what standards I need to uphold if I am building an online presence. Oh well... the journey is long. I will do my best not to repeat the same mistakes. Thank you for holding me accountable.

**Pull request merged**
