### PR TITLE
Added support for Azure OpenAI

### PR DESCRIPTION
**Pull request by roberto-mardeni**
Adds the configuration options to allow this framework to connect to Azure OpenAI instead of public OpenAI APIs.

### CODE REVIEW

**Comment by jarodsmk** [comment]
@lucgagan Would you mind reviewing this? Seems that it would also resolve https://github.com/lucgagan/auto-playwright/issues/6

**Comment by lucgagan** [comment]
Just needs to pass the tests. @roberto-mardeni I can help to get this across the line.

**Comment by roberto-mardeni** [comment]
Will review this week and fix to pass the testsRoberto MardeniSent from iPhoneOn Apr 26, 2024, at 9:20 PM, Luc Gagan ***@***.***> wrote:﻿
Just needs to pass the tests. @roberto-mardeni I can help to get this across the line.

**Comment by roberto-mardeni** [comment]
@lucgagan workflow still pending approval, can you help trigger it?

**Pull request merged**
